### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by rleenay** [lyellbio/codon-harmony#45]
Hello, 

I am trying to install this tool using `pip` and I'm getting an error message that I cannot quite figure out:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rleenay/.local/lib/python2.7/site-packages/codon_harmony/__init__.py", line 4, in <module>
    from .codon_harmony import main as runner
  File "/home/rleenay/.local/lib/python2.7/site-packages/codon_harmony/codon_harmony.py", line 11, in <module>
    from .util import codon_use, logging, log_levels, seq_opt
ImportError: No module named util
```

It looks as though the install proceeds without issue, I installed it with the `--user` flag, and I can see it under my available modules within python. Do you have any idea why this error would pop out?

**Comment by rleenay** [comment]
So I was able to get a complete install, and everything seems to be working except I'm finding an issue with the codon tables:

```~/codon-harmony$ conda env create -f environment.yml
Collecting package metadata: done
Solving environment: failed

ResolvePackageNotFound:
  - python_codon_tables==0.1.8
```

In the install, everything proceeds without error, including the `python_codon_tables`. Is there an issue with the base code within these codon tables that is not functioning? Or is this something on my end?

**Comment by weitzner** [comment]
I believe the issue you've encountered is due to the `python-codon-tables` being unavailable on public conda channels. You should be able to create a virtual environment with each of the requirements pip-installed and keep going 👍
